version: '3.7'

services:
  prometheus:
    image: prom/prometheus:v2.44.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./docker_volumes/monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  # grafana:
  #   image: grafana/grafana:9.5.2
  #   container_name: grafana
  #   ports:
  #     - "3000:3000"
  #   restart: unless-stopped
  #   volumes:
  #     - ./docker_volumes/monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources

  server:
    image: registry.gitlab.com/amirr01/mq-sad-1402-1-server:latest
    volumes:
      - ./docker_volumes/server/application.properties:/app/application.properties
    ports:
      - "8085:8080"

  broker1:
    image: registry.gitlab.com/amirr01/mq-sad-1402-1-broker:latest
    volumes:
      - ./docker_volumes/broker1/data:/app/data
      - ./docker_volumes/broker1/application.properties:/app/application.properties
    ports:
      - "8081:8080"
  broker2:
    image: registry.gitlab.com/amirr01/mq-sad-1402-1-broker:latest
    volumes:
      - ./docker_volumes/broker2/data:/app/data
      - ./docker_volumes/broker2/application.properties:/app/application.properties
    ports:
      - "8082:8080"
  broker3:
    image: registry.gitlab.com/amirr01/mq-sad-1402-1-broker:latest
    volumes:
      - ./docker_volumes/broker3/data:/app/data
      - ./docker_volumes/broker3/application.properties:/app/application.properties
    ports:
      - "8083:8080"

  producer1:
    image: registry.gitlab.com/amirr01/mq-sad-1402-1-java-client:latest
    volumes:
      - ./docker_volumes/producer1/application.properties:/app/application.properties
    ports:
      - "8090:8080"
  producer2:
    image: registry.gitlab.com/amirr01/mq-sad-1402-1-java-client:latest
    volumes:
      - ./docker_volumes/producer2/application.properties:/app/application.properties
    ports:
      - "8091:8080"
  consumer1:
    image: registry.gitlab.com/amirr01/mq-sad-1402-1-java-client:latest
    volumes:
      - ./docker_volumes/consumer1/application.properties:/app/application.properties
    ports:
      - "8092:8080"
  consumer2:
    image: registry.gitlab.com/amirr01/mq-sad-1402-1-java-client:latest
    volumes:
      - ./docker_volumes/consumer2/application.properties:/app/application.properties
    ports:
      - "8093:8080"

#  5403  vim docker-compose.yml
#  5404  docker compose up -d --remove-orphans
#  5405  docker compose ls
#  5406  docker compose ps
#  5407  vim docker-compose.yml
#  5408  docker compose up -d app --scale 10
#  5409  docker compose up -d app --scale app=10
#  5410  docker compose exec nginx bash
#  5411  docker compose ps
#  5412  vim docker-compose.yml
#  5413  docker compose up -d --remove-orphans
#  5414  vim docker-compose.yml
#  5415  docker compose up -d
#  5416  docker compose exec nginx bash
#  5417  curl -v http://app:80
#  5418  docker compose ps
#  5419  docker compose exec zk bash
#  5420  history