package MQproject.broker.model.message;

public enum MessageType {
    REGISTER_BROKER,
    INFORM_ABOUT_PRODUCER,
    INFORM_ABOUT_CONSUMER,
    ADD_PARTITION,
    MOVE_PARTITION,
    CLONE_PARTITION,
    REMOVE_PARTITION,
    BECOME_PARTITION_LEADER,

    PRODUCE_MESSAGE,
    CONSUME_MESSAGE,

    REPLICATE_MESSAGE,
    UPDATE_HEAD_INDEX,
    RECEIVE_PARTITION_BECOME_LEADER,
    RECEIVE_PARTITION_BECOME_REPLICA,

    LIST_BROKERS,


    REMOVE_BROKER,
    ADD_REPLICA,
    REMOVE_REPLICA,
    ADD_CLIENT,
    REMOVE_CLIENT,
    ADD_MESSAGE,
    REMOVE_MESSAGE,
    ADD_SUBSCRIPTION,
    REMOVE_SUBSCRIPTION,
    ADD_CONSUMER,
    REMOVE_CONSUMER,
    ADD_PRODUCER,
    REMOVE_PRODUCER,
    ADD_METRICS,
    REMOVE_METRICS,
    GET_METRICS,
    RESET_METRICS,
    RUN_MONITORING,
    STOP_MONITORING
}
