scrape_configs:
  - job_name: 'MyAppMetrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['docker.for.mac.localhost:9001']
        labels:
          application: 'My Spring Boot Application'